/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcial;

import Clases.Vendedor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;
import parcial.conexion;
import Clases.LlenarObjetos;
import Clases.Procedimiento;
import Clases.Sucursal;
import Clases.Ciudad;
import java.awt.Toolkit;
import java.sql.Date;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PANCHY
 * @author PANCHY
 */
public final class principal extends javax.swing.JFrame {

    Connection cn;
    conexion conn = new conexion();
    PreparedStatement s;
    ResultSet rs;
    DefaultTableModel dtm;
    LlenarObjetos objLlenar = new LlenarObjetos();
    Procedimiento objProd = new Procedimiento();
    int id, idProd, cant,idsucursal, idciudad;
    DefaultTableModel modelo;
    double precio;
    int ite = 0;
    String[] camposRepresentante;
    
       Calendar fecha = Calendar.getInstance();
        int anho = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DATE);
//        String mon = String.valueOf(mes);
//      String year = String.valueOf(anho);
//        String day = String.valueOf(dia);
    
    

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();

        LlenarTablaVenta();
       
        objLlenar.mostrarVendedores(cbvendedor);
        objLlenar.mostrarSucursales(cbsucursal);
         objLlenar.mostrarCiudad(cbciudad);
        modelo = null;
        
     mes = mes+1;
      txtfecha.setText(dia + "-"+mes +"-"+anho);
     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtdia3 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableVend = new javax.swing.JTable();
        cbvendedor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtproducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcant = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableVentaFinal = new javax.swing.JTable();
        btnventa = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnVentaFinal = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cbsucursal = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbciudad = new javax.swing.JComboBox<>();
        txtfecha = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        btnvendedor = new javax.swing.JButton();
        txtprueba = new javax.swing.JTextField();
        txtdia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtmes = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtyear = new javax.swing.JTextField();
        txtdia2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtmes2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtyear2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtdiaC = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtmesC = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtyearC = new javax.swing.JTextField();
        txtdia2C = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtmes2C = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtyear2C = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        btncliente = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        txtdia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdia3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableVend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Marca", "Modelo", "Precio", "Cantidad"
            }
        ));
        tableVend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVendMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableVend);

        cbvendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        cbvendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbvendedorMouseClicked(evt);
            }
        });

        jLabel1.setText("Producto:");

        jLabel2.setText("Precio Unitario:");

        jLabel3.setText("Cantidad:");

        tableVentaFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tableVentaFinal);

        btnventa.setText("Realizar Venta");
        btnventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventaActionPerformed(evt);
            }
        });

        btncancelar.setText("Cancelar");

        jLabel4.setText("Vendedor");

        btnVentaFinal.setText("Finalizar venta");
        btnVentaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaFinalActionPerformed(evt);
            }
        });

        jLabel11.setText("Sucursal");

        cbsucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        cbsucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbsucursalMouseClicked(evt);
            }
        });

        jLabel12.setText("Ciudad");

        cbciudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        cbciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbciudadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcant))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(58, 58, 58)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbsucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnventa)
                                .addGap(33, 33, 33)
                                .addComponent(btncancelar))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVentaFinal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(cbsucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnventa)
                    .addComponent(btncancelar))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnVentaFinal)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ventas", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("TOTAL VENTAS POR VENDEDOR");

        jLabel6.setText("Rango de fechas entre:");

        jLabel7.setText("y");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendedor", "Total Vendido"
            }
        ));
        jScrollPane6.setViewportView(jTable4);

        btnvendedor.setText("Ver");
        btnvendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvendedorActionPerformed(evt);
            }
        });

        txtprueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpruebaActionPerformed(evt);
            }
        });

        txtdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiaActionPerformed(evt);
            }
        });
        txtdia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdiaKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel13.setText("-");

        txtmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmesActionPerformed(evt);
            }
        });
        txtmes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmesKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel14.setText("-");

        txtyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyearActionPerformed(evt);
            }
        });
        txtyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtyearKeyTyped(evt);
            }
        });

        txtdia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdia2ActionPerformed(evt);
            }
        });
        txtdia2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdia2KeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel15.setText("-");

        txtmes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmes2ActionPerformed(evt);
            }
        });
        txtmes2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmes2KeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel16.setText("-");

        txtyear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyear2ActionPerformed(evt);
            }
        });
        txtyear2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtyear2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdia2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmes2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtyear2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(btnvendedor))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtprueba, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(btnvendedor)
                    .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtmes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtyear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setText("TOTAL VENTAS POR CLIENTE");

        jLabel9.setText("Rango de fechas entre:");

        jLabel10.setText("y");

        txtdiaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiaCActionPerformed(evt);
            }
        });
        txtdiaC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdiaCKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel17.setText("-");

        txtmesC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmesCActionPerformed(evt);
            }
        });
        txtmesC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmesCKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel18.setText("-");

        txtyearC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyearCActionPerformed(evt);
            }
        });
        txtyearC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtyearCKeyTyped(evt);
            }
        });

        txtdia2C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdia2CActionPerformed(evt);
            }
        });
        txtdia2C.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdia2CKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel19.setText("-");

        txtmes2C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmes2CActionPerformed(evt);
            }
        });
        txtmes2C.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmes2CKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel20.setText("-");

        txtyear2C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyear2CActionPerformed(evt);
            }
        });
        txtyear2C.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtyear2CKeyTyped(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Total Vendido"
            }
        ));
        jScrollPane7.setViewportView(jTable5);

        btncliente.setText("Ver");
        btncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdiaC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmesC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtyearC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdia2C, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmes2C, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtyear2C, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btncliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtdiaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtmesC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtyearC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtdia2C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtmes2C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtyear2C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncliente))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Total ventas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbvendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbvendedorMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbvendedorMouseClicked

    private void btnventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventaActionPerformed
        // TODO add your handling code here:
        if (ite == 0) {
            String[] titulo = {"ID producto", "Producto", "cantidad", "Precio"};
            modelo = new DefaultTableModel(null, titulo);
            camposRepresentante = new String[5];
            ite = 1;
        }
        camposRepresentante[0] = idProd + "";
        camposRepresentante[1] = txtproducto.getText();
        camposRepresentante[2] = cant + "";
        camposRepresentante[3] = precio + "";
        modelo.addRow(camposRepresentante);
        tableVentaFinal.setModel(modelo);
    }//GEN-LAST:event_btnventaActionPerformed

    private void btnVentaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaFinalActionPerformed
        // TODO add your handling code here:
        if (this.tableVentaFinal.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Debe agregar primero productos a la tabla");
        } else {
            id = Integer.parseInt(cbvendedor.getItemAt(cbvendedor.getSelectedIndex()).getId() + "");
            idsucursal = Integer.parseInt(cbsucursal.getItemAt(cbsucursal.getSelectedIndex()).getId() + "");
             idciudad = Integer.parseInt(cbciudad.getItemAt(cbciudad.getSelectedIndex()).getId() + "");
            int[] nuevoArray = new int[tableVentaFinal.getRowCount()];
            int[] nuevoArrayD = new int[tableVentaFinal.getRowCount()];
            for (int i = 0; i <= tableVentaFinal.getRowCount() - 1; i++) {
                int idp = Integer.parseInt(tableVentaFinal.getValueAt(i, 0) + "");
                int cantid = Integer.parseInt(tableVentaFinal.getValueAt(i, 2) + "");
                nuevoArray[i] = idp;
                nuevoArrayD[i] = cantid;
            }
            try {
                objProd.InsertarVenta(id, idsucursal, idciudad, 1, nuevoArray, nuevoArrayD, dia, mes, anho);
                JOptionPane.showMessageDialog(this, "vendidos con éxito");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnVentaFinalActionPerformed

    private void tableVendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVendMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tableVend.getModel();
        txtproducto.setText(String.valueOf(modelo.getValueAt(tableVend.getSelectedRow(), 1) + ""));
        idProd = Integer.parseInt(String.valueOf(modelo.getValueAt(tableVend.getSelectedRow(), 0) + ""));
        cant = Integer.parseInt(String.valueOf(modelo.getValueAt(tableVend.getSelectedRow(), 4) + ""));
        precio = Integer.parseInt(String.valueOf(modelo.getValueAt(tableVend.getSelectedRow(), 5) + ""));
        txtcant.setText(cant + "");
        txtprecio.setText(precio + "");
    }//GEN-LAST:event_tableVendMouseClicked

    private void cbsucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbsucursalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsucursalMouseClicked

    private void cbciudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbciudadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbciudadMouseClicked

    private void btnvendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvendedorActionPerformed
         LlenarTablaVendedor();
    }//GEN-LAST:event_btnvendedorActionPerformed

    private void txtdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiaActionPerformed

    private void txtmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmesActionPerformed

    private void txtyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyearActionPerformed

    private void txtdia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdia2ActionPerformed

    private void txtmes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmes2ActionPerformed

    private void txtdia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdia3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdia3ActionPerformed

    private void txtyear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyear2ActionPerformed

    private void txtpruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpruebaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpruebaActionPerformed

    private void txtdiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiaKeyTyped
        char c = evt.getKeyChar();
        if(txtdia.getText().length()==2)
        {
          evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        if(c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_txtdiaKeyTyped

    private void txtmesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmesKeyTyped
         char c = evt.getKeyChar();
        if(txtmes.getText().length()==2)
        {
          evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        if(c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_txtmesKeyTyped

    private void txtyearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtyearKeyTyped
        char c = evt.getKeyChar();
        if(txtyear.getText().length()==4)
        {
          evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        if(c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_txtyearKeyTyped

    private void txtdia2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdia2KeyTyped
        char c = evt.getKeyChar();
        if(txtdia2.getText().length()==2)
        {
          evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        if(c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_txtdia2KeyTyped

    private void txtmes2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmes2KeyTyped
        char c = evt.getKeyChar();
        if(txtmes2.getText().length()==2)
        {
          evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        if(c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_txtmes2KeyTyped

    private void txtyear2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtyear2KeyTyped
         char c = evt.getKeyChar();
        if(txtyear2.getText().length()==4)
        {
          evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        if(c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_txtyear2KeyTyped

    private void txtdiaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiaCActionPerformed

    private void txtdiaCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiaCKeyTyped
         char c = evt.getKeyChar();
        if(txtdiaC.getText().length()==2)
        {
          evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        if(c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_txtdiaCKeyTyped

    private void txtmesCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmesCActionPerformed
        
    }//GEN-LAST:event_txtmesCActionPerformed

    private void txtmesCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmesCKeyTyped
           char c = evt.getKeyChar();
        if(txtmesC.getText().length()==2)
        {
          evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        if(c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_txtmesCKeyTyped

    private void txtyearCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyearCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyearCActionPerformed

    private void txtyearCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtyearCKeyTyped
      char c = evt.getKeyChar();
        if(txtyearC.getText().length()==4)
        {
          evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        if(c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_txtyearCKeyTyped

    private void txtdia2CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdia2CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdia2CActionPerformed

    private void txtdia2CKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdia2CKeyTyped
            char c = evt.getKeyChar();
        if(txtdia2C.getText().length()==2)
        {
          evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        if(c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_txtdia2CKeyTyped

    private void txtmes2CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmes2CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmes2CActionPerformed

    private void txtmes2CKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmes2CKeyTyped
       char c = evt.getKeyChar();
        if(txtmes2C.getText().length()==2)
        {
          evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        if(c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_txtmes2CKeyTyped

    private void txtyear2CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyear2CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyear2CActionPerformed

    private void txtyear2CKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtyear2CKeyTyped
        char c = evt.getKeyChar();
        if(txtyear2C.getText().length()==4)
        {
          evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        if(c<'0' || c>'9')
            evt.consume();
    }//GEN-LAST:event_txtyear2CKeyTyped

    private void btnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclienteActionPerformed
         LlenarTablaCliente();
    }//GEN-LAST:event_btnclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });

    }

    public void LlenarTablaVenta() {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            this.tableVend.setModel(modelo);
            s = conn.getConnection().prepareStatement("select p.id_producto,  p.nombre,  p.marca,p.modelo, i.precio, i.cantidad, i.costo from producto_d p "
                    + "inner join hechos_compra_d hc on hc.id_producto=p.id_producto "
                    + "inner join inventario_d i on i.id_inventario= hc.id_inventario");
            rs = s.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int cantcolumnas = rsmd.getColumnCount();

            for (int i = 1; i < cantcolumnas; i++) {
                modelo.addColumn(rsmd.getColumnLabel(i));

            }

            while (rs.next()) {
                Object[] fila = new Object[cantcolumnas];
                for (int i = 0; i < cantcolumnas; i++) {
                    fila[i] = rs.getObject(i + 1);

                }
                modelo.addRow(fila);
            }
            rs.close();
            cn.close();
        } catch (Exception e) {
        }

    }

    public void LlenarTablaVendedor() {
        try {
            
             int dia = Integer.parseInt(txtdia.getText());
             int mes = Integer.parseInt(txtmes.getText());
             int anho = Integer.parseInt(txtyear.getText());
             int dia2 = Integer.parseInt(txtdia2.getText());
             int mes2 = Integer.parseInt(txtmes2.getText());
             int anho2 = Integer.parseInt(txtyear2.getText());
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable4.setModel(modelo);
            s = conn.getConnection().prepareStatement("select v.nombre || ' ' || v.apellido as vendedor, sum(vd.total) as total, v.nombre from hechos_venta_d hv\n"
                    + "inner join vendedor_d v on v.id_vendedor = hv.id_vendedor\n"
                    + "inner join venta_d vd on vd.id_venta = hv.id_venta\n"
                    + "inner join tiempo_d t on t.id_tiempo= hv.id_tiempo\n"
                    + "where v.id_vendedor = hv.id_vendedor  and dia between "+ dia + " and "+ dia2 +" and mes BETWEEN " + mes + " and " + mes2 + " and anho BETWEEN "+ anho + " and " + anho2 + " \n" 
                    + " GROUP BY total, v.nombre || ' ' || v.apellido, ' ', v.nombre");
            rs = s.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int cantcolumnas = rsmd.getColumnCount();

            for (int i = 1; i < cantcolumnas; i++) {
                modelo.addColumn(rsmd.getColumnLabel(i));

            }

            while (rs.next()) {
                Object[] fila = new Object[cantcolumnas];
                for (int i = 0; i < cantcolumnas; i++) {
                    fila[i] = rs.getObject(i + 1);

                }
                modelo.addRow(fila);
            }
            rs.close();
            cn.close();
        } catch (Exception e) {
        }
    }

    public void LlenarTablaCliente() {
        try {
            int diaC = Integer.parseInt(txtdiaC.getText());
             int mesC = Integer.parseInt(txtmesC.getText());
             int anhoC = Integer.parseInt(txtyearC.getText());
             int dia2C = Integer.parseInt(txtdia2C.getText());
             int mes2C = Integer.parseInt(txtmes2C.getText());
             int anho2C = Integer.parseInt(txtyear2C.getText());
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable5.setModel(modelo);
            s = conn.getConnection().prepareStatement("select c.nombre || ' ' || c.apellido as Cliente, sum(vd.total) as total, c.nombre from hechos_venta_d hv\n"
                    + "inner join cliente_d c on c.id_cliente = hv.id_cliente\n"
                    + "inner join venta_d vd on vd.id_venta = hv.id_venta\n"
                    + "inner join tiempo_d t on t.id_tiempo= hv.id_tiempo\n"
                    + "where c.id_cliente = hv.id_cliente and dia between "+ diaC + " and "+ dia2C +" and mes BETWEEN " + mesC + " and " + mes2C + " and anho BETWEEN "+ anhoC + " and " + anho2C + " \n"
                    + "GROUP BY total, c.nombre || ' ' || c.apellido, ' ', c.nombre");
            rs = s.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int cantcolumnas = rsmd.getColumnCount();

            for (int i = 1; i < cantcolumnas; i++) {
                modelo.addColumn(rsmd.getColumnLabel(i));

            }

            while (rs.next()) {
                Object[] fila = new Object[cantcolumnas];
                for (int i = 0; i < cantcolumnas; i++) {
                    fila[i] = rs.getObject(i + 1);

                }
                modelo.addRow(fila);
            }
            rs.close();
            cn.close();
        } catch (Exception e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVentaFinal;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncliente;
    private javax.swing.JButton btnvendedor;
    private javax.swing.JButton btnventa;
    private javax.swing.JComboBox<Ciudad> cbciudad;
    private javax.swing.JComboBox<Sucursal> cbsucursal;
    private javax.swing.JComboBox<Vendedor> cbvendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTable tableVend;
    private javax.swing.JTable tableVentaFinal;
    private javax.swing.JTextField txtcant;
    private javax.swing.JTextField txtdia;
    private javax.swing.JTextField txtdia2;
    private javax.swing.JTextField txtdia2C;
    private javax.swing.JTextField txtdia3;
    private javax.swing.JTextField txtdiaC;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtmes;
    private javax.swing.JTextField txtmes2;
    private javax.swing.JTextField txtmes2C;
    private javax.swing.JTextField txtmesC;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtproducto;
    private javax.swing.JTextField txtprueba;
    private javax.swing.JTextField txtyear;
    private javax.swing.JTextField txtyear2;
    private javax.swing.JTextField txtyear2C;
    private javax.swing.JTextField txtyearC;
    // End of variables declaration//GEN-END:variables
}
;
